steps:
# ────────── 1. BUILD ──────────
- name: gcr.io/cloud-builders/docker
  env:
  - NPM_CONFIG_LEGACY_PEER_DEPS=true
  args:
  - build
  - -t
  - gcr.io/$PROJECT_ID/highlaunchpad:$COMMIT_SHA

  # ---- build-args (each one is its own list item) ----
  - --build-arg
  - NEXT_PUBLIC_FIREBASE_API_KEY=$_NEXT_PUBLIC_FIREBASE_API_KEY
  - --build-arg
  - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
  - --build-arg
  - NEXT_PUBLIC_FIREBASE_PROJECT_ID=$_NEXT_PUBLIC_FIREBASE_PROJECT_ID
  - --build-arg
  - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
  - --build-arg
  - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
  - --build-arg
  - NEXT_PUBLIC_FIREBASE_APP_ID=$_NEXT_PUBLIC_FIREBASE_APP_ID

  # ---- finally the build context (dot) ----
  - .

# ────────── 2. PUSH ──────────
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - gcr.io/$PROJECT_ID/highlaunchpad:$COMMIT_SHA

# ────────── 3. DEPLOY ──────────
- name: gcr.io/cloud-builders/gcloud
  args:
  - run
  - deploy
  - highlaunchpad
  - --image=gcr.io/$PROJECT_ID/highlaunchpad:$COMMIT_SHA
  - --region=us-central1
  - --platform=managed
  - --allow-unauthenticated
  - --port=3000
  - --update-secrets=FIREBASE_SERVICE_ACCOUNT=firebase-service-key:latest

images:
- gcr.io/$PROJECT_ID/highlaunchpad:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
