steps:
  # Access Firebase service account from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret="firebase-service-key" > /workspace/firebase-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=/workspace/firebase-key.json

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/highlaunchpad:$COMMIT_SHA'
      - '.'
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/firebase-key.json'

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/highlaunchpad:$COMMIT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'highlaunchpad'
      - '--image=gcr.io/$PROJECT_ID/highlaunchpad:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/firebase-key.json'

# Grant Cloud Build access to Secret Manager
options:
  logging: CLOUD_LOGGING_ONLY

# Required IAM permissions for Cloud Build service account:
# - Secret Manager Secret Accessor
# - Cloud Run Developer  
# - Service Account User