steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/highlaunchpad:$COMMIT_SHA'
      - '.'
    timeout: '1200s'

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/highlaunchpad:$COMMIT_SHA'
    timeout: '600s'

  # Deploy to Cloud Run with secret as environment variable
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'highlaunchpad'
      - '--image=gcr.io/$PROJECT_ID/highlaunchpad:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production,FIREBASE_CONFIG=$FIREBASE_SERVICE_ACCOUNT'
    secretEnv: ['FIREBASE_SERVICE_ACCOUNT']
    timeout: '600s'

# Use availableSecrets to access your existing secret
availableSecrets:
  secretManager:
    - versionName: 'projects/$PROJECT_ID/secrets/firebase-service-key/versions/latest'
      env: 'FIREBASE_SERVICE_ACCOUNT'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/highlaunchpad:$COMMIT_SHA'