# This file is deprecated as the project is now configured for Firebase Hosting.
# Please use the Firebase CLI for deployments (`firebase deploy`).
# The configuration for Firebase Hosting can be found in `firebase.json`.
