steps:
  # ---------- Build ----------
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/highlaunchpad:$COMMIT_SHA', '.']
  
  # ---------- Push ----------
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/highlaunchpad:$COMMIT_SHA']
  
  # ---------- Deploy ----------
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - highlaunchpad  # Cloud Run service name
      - --image=gcr.io/$PROJECT_ID/highlaunchpad:$COMMIT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --port=3000
      # expose secret as env var FIREBASE_SERVICE_ACCOUNT
      - --update-secrets=FIREBASE_SERVICE_ACCOUNT=firebase-service-key:latest

images:
  - gcr.io/$PROJECT_ID/highlaunchpad:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY          # satisfies rule (c)
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET   # also satisfies rule (b)
